/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repository
*/

var o=Object.defineProperty;var g=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var y=(i,e)=>{for(var t in e)o(i,t,{get:e[t],enumerable:!0})},m=(i,e,t,s)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of d(e))!c.call(i,n)&&n!==t&&o(i,n,{get:()=>e[n],enumerable:!(s=g(e,n))||s.enumerable});return i};var h=i=>m(o({},"__esModule",{value:!0}),i);var u={};y(u,{default:()=>a});module.exports=h(u);var S=require("obsidian"),E={headingNumbering:!0,titleBlock:!0,baseFontSize:"11pt",paperSize:"letter"},l={letter:{size:"letter",margin:"1in"},a4:{size:"A4",margin:"25mm"}},r="latex-look-heading-numbers",p="latex-look-title-block-enabled",z="latex-look-print-page-style",a=class extends S.Plugin{constructor(){super(...arguments);this.printStyleEl=null}async onload(){await this.loadSettings(),this.applySettings()}onunload(){var s;let t=document.body;t.classList.remove(r,p),t.style.removeProperty("--latex-look-font-size"),(s=this.printStyleEl)==null||s.remove(),this.printStyleEl=null}async loadSettings(){this.settings=Object.assign({},E,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}applySettings(){let t=document.body;t.classList.toggle(r,this.settings.headingNumbering),t.classList.toggle(p,this.settings.titleBlock),t.style.setProperty("--latex-look-font-size",this.settings.baseFontSize),this.updatePrintPageStyle()}updatePrintPageStyle(){var s;let t=(s=l[this.settings.paperSize])!=null?s:l.letter;this.printStyleEl||(this.printStyleEl=document.createElement("style"),this.printStyleEl.id=z,document.head.appendChild(this.printStyleEl)),this.printStyleEl.textContent=`@media print {
  @page {
    size: ${t.size};
    margin: ${t.margin};
  }
}`}};
